#ifndef MENU_H
#define MENU_H

#include "rpg.h"
#include "window.h"

typedef struct _menu_option {
    char name[100];
    void *ptr;
    int is_selected;
} menu_option;

#define init_menu_option(x) menu_option x = {.name={ '\0' }, .ptr = NULL, .is_selected = 0 };

// ASCII art generated by tool by patorjk,
// http://patorjk.com/software/taag/
void render_main_menu(window_info *wi);

#endif