#ifndef MENU_H
#define MENU_H

#include "rpg.h"
#include "window.h"
#include "character.h"

typedef struct _menu_option {
    char name[100];
    void (*ptr)(void);
    int name_length;
    int is_selected;
} menu_option;

#define init_menu_option(x) menu_option x = {.name={ '\0' }, .ptr = NULL, .name_length = 0, .is_selected = 0 };

void init_main_menu_options(void (*ptr[])());

void create_menu_option(menu_option *m, char *name, void *ptr, int is_selected);

void select_menu_option(int num);

// ASCII art generated by tool by patorjk,
// http://patorjk.com/software/taag/
void render_main_menu(window_info *wi);

void process_menu_input(int input, int *selected_option);

void init_character_creation_options(void);

void select_cc_menu_option(int selected_field);

void render_character_creation_menu(window_info *wi, int selected_option, character *pc);

void prep_formatted_attribute(int id, character *pc, char *dest);

void print_status_bar(int y, int x, char *name, short color_code, int actual, int nominal);

void gets_window(window_info *wi, char *name, char *dest);

void get_character_attribute(character *pc, int selected_option);

void race_selection_window(window_info *wi, character *pc);

void class_selection_window(window_info *wi, character *pc);

// global menu options array
extern enum game_mode mode;
menu_option menu_options[100];
int num_main_menu_options;
menu_option character_creation_options[100];
int num_cc_options;

#endif